version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  app:
    image: flv_email_service
    environment:
      - PORT=5500
      - MONGO_URI=mongodb://mongo:27017/flv_email_service
      - API_URL=http://127.0.0.1:5500
    ports:
      - 1500:5500
    depends_on:
     - mongo